version: "2.4"

services:
  worker:
    build:
      context: ./worker
    # image: denoland/deno:alpine-1.38.3
    command: deno run -A --watch ./server.ts
    working_dir: /app/worker
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 5s
      timeout: 1s
    environment:
      - "DENO_DIR=/deno"
      - "DENO_INSTALL_ROOT=/deno"
      - "PORT=3000"
      - "APP_FQDN=${APP_FQDN:-server1.localhost}"
      - "PATH=$PATH:/DENO_INSTALL_ROOT/bin"
    expose:
      - 3000
    volumes:
      - deno:/deno
      - ./worker:/app/worker
      - ./editor/src:/app/editor/src
    logging:
      driver: ${LOGGING_SERVER:-local}
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-server.tls=true
      - traefik.http.routers.app-server.rule=Host("${APP_FQDN:-server1.localhost}")

  editor:
    build:
      context: ./editor
      # dockerfile: Dockerfile
    command: just dev
    working_dir: /app/editor
    healthcheck:
      test: curl --fail http://localhost:4440 || exit 1
      interval: 5s
      timeout: 1s
    environment:
      - "DENO_DIR=/deno"
      - "DENO_INSTALL_ROOT=/deno"
      - "APP_PORT_BROWSER=4440"
      - "APP_PORT=${APP_PORT:-443}"
      - "APP_FQDN=${APP_FQDN:-server1.localhost}"
      - BASE=editor
    expose:
      - 4440
    volumes:
      - deno:/deno
      - node_modules:/app/editor/node_modules
      - ./editor/dist:/app/editor/dist
      - ./editor/public:/app/editor/public
      - ./editor/src:/app/editor/src
      - ./editor/index.html:/app/editor/index.html
      - ./editor/justfile:/app/editor/justfile
      - ./editor/package.json:/app/editor/package.json
      - ./editor/package-lock.json:/app/editor/package-lock.json
      - ./editor/tsconfig.json:/app/editor/tsconfig.json
      - ./editor/vite.config.ts:/app/editor/vite.config.ts
      - ./.git:/app/.git
    logging:
      driver: ${LOGGING_SERVER:-local}
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-editor.tls=true
      - traefik.http.routers.app-editor.rule=Host("${APP_FQDN:-server1.localhost}") && PathPrefix(`/editor`)

  traefik:
    image: "traefik:v2.10.7"
    container_name: "traefik-connect-metaframe-mdv2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"
    ports:
      # HTTPS / SSL port
      - "${APP_PORT:-443}:443"
      # The Traefik Web UI port (enabled by api:insecure: true in traefik.yml)
      - "${TRAEFIK_WEB_UI_PORT:-8080}:8080"
    volumes:
      - ./.traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./.traefik/config.yml:/etc/traefik/config.yml:ro
      - ./.traefik/certs:/etc/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  deno:
    driver: local
  node_modules:
    driver: local
